project:
  type: website

website:
  title: "Lê Quang Phú"
  site-url: https://lequangphu.github.io/
  google-analytics: "G-S7Y9SX5DXE"
  open-graph: true
  twitter-card: 
    creator: "@0xphu"
  repo-url: https://github.com/lequangphu/lequangphu.github.io
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog
      - about.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/0xphu
      - icon: github
        href: https://github.com/lequangphu

theme: zephyr

execute:
  freeze: auto
