---
title: 'Uniswap Meme Coin Mania'
description: ''
date: '2023-06-01'
categories: [analysis, crypto]
image: ''
---

# Context

As of May 20, 2023, there are 706 meme coins listed on [Coinmarketcap](https://coinmarketcap.com/view/memes/).

> What is a meme coin?
>
> -   A meme coin is a cryptocurrency that doesn't take itself as seriously as leading digital currencies like Bitcoin and Ethereum. Dogecoin (DOGE) - widely regarded as the first meme cryptocurrency.
>
> -   A meme coin doesn't need to have a purpose that is as closely tied to their underlying value, like Bitcoin and Ethereum. A meme coin often seems to have the sole purpose of "going to the moon," a phrase popularized by Dogecoin's skyrocketing price in early 2021.

Started on Apr 14, interest in meme coins surged, led by PEPE, TURBO, and WOJAK. The meme coin mania has pushed Uniswap' trading volume above Coinbase's trading volume in recent days.

## In this analysis

I'll answer a few questions below:

-   Did the increase in popularity of Memecoins attract new traders to the Uniswap platform?

-   Who are the participants actively engaging with Memecoins on Uniswap? How are the whales behaving, do they have a big impact on the market?

-   Has the introduction of Memecoins led to an increase or decrease in the number of pairs created on Uniswap? Are there any notable trends or preferences in terms of the Memecoin pairs being created?

-   Did the rise of Memecoins have any discernible effect on the activity and liquidity of "normal" pairs on Uniswap? Are there any correlations or shifts in trading behavior?

## Method

-   PEPE, TURBO, and WOJAK represent all of meme coins on Ethereum.

-   Traders in this context are traders who swap on Uniswap.

# Key Highlights

# The Rise of Meme

On Ethereum, at its peak, meme pools acounted for 1/3 in total trading volume.

<iframe src="https://dune.com/embeds/2492014/4099854" width="800" height="400"></iframe>

And their share is a bit higher at 37% in total trader.

<iframe src="https://dune.com/embeds/2492014/4099858" width="800" height="400"></iframe>

While only accounted for up to 1/5 in total transaction. Which means those who joined the mania were more aggressive in trading size than those who didn't.

<iframe src="https://dune.com/embeds/2492014/4102957" width="800" height="400"></iframe>

## How much of those happened on Uniswap?

The mania happened on 6 Dexs, and only 2% of trading activities didn't happen on Uniswap as seen in the bubble chart below. The pink buble is so much bigger, and so far away from the rest.

<iframe src="https://dune.com/embeds/2493840/4102979" width="800" height="400"></iframe>

So the mania on Ethereum was basically the mania on Uniswap. Let's look into its effects on Uniswap.

# Effects On Uniswap

### New Trader

The rise in total new trader was highly correlated to the rise of % share of meme pools in total new trader. At its peak, meme pools accounted for 2/3 of total new trader.

<iframe src="https://dune.com/embeds/2493899/4103138" width="800" height="400"></iframe>

In a few days that trading activities of meme coins surged, % share of new trader in meme pools rose higher than that in other pools, the difference can be as high as 2x (34% vs. 17%).

<iframe src="https://dune.com/embeds/2493956/4103153" width="800" height="400"></iframe>

Thus, it is safe to say that the mania did attract new trader to Uniswap.

However, it raised another question, which is 👇

### How sticky are these meme traders?

Retention Rate
: % of a cohort return (to swap on Uniswap).

Retention rate of meme traders in the first 3 weeks is 2x of Uniswap average. However, from week 4th, the trend appears to drop faster than Uniswap average.

<iframe src="https://dune.com/embeds/2496227/4107513" width="800" height="400"></iframe>

So meme traders are more sticky than the average trader on Uniswap, at least in their first 3 weeks.

### When they returned, what did they return for?

When meme traders returned, more than half of their acitivities were in the meme pools. However, those activities only accounted for 40% in their total return volume.

:::{layout="[45,-10,45]"}

<iframe src="https://dune.com/embeds/2496472/4107727" width="400" height="400"></iframe>

<iframe src="https://dune.com/embeds/2496472/4107714" width="400" height="400"></iframe>

:::

Of 60% in total return volume which was not in meme pools, almost half was in pools made of 2 in 3 most popular coins: USDC, USDT, and WETH.

<iframe src="https://dune.com/embeds/2499183/4112381" width="800" height="400"></iframe>

### Summary

In this section, I examined trading activities of new traders in the meme pools. The data shows us that the rise of meme did attract new traders to Uniswap (contributed as high as 2/3 in total new traders). New traders in meme pools are also more sticky compare to average traders of Uniswap.

Next, let's examine activities of traders in the meme pools.

## Trader of Meme

### Who are they?

<iframe src="https://dune.com/embeds/2499355/4112994" width="800" height="400"></iframe>

:::{layout="[45,-10,45]"}

<iframe src="https://dune.com/embeds/2499355/4113067" width="400" height="400"></iframe>

<iframe src="https://dune.com/embeds/2499355/4113072" width="400" height="400"></iframe>

:::
